node('master'){
  def tf
  stage('Show build plan') {
    /* Pull aws infrastructure builder repo */

    tf = docker.image('alpine').inside('--user=root -e AWS_ACCESS_KEY_ID=AKIAIIGMIBUV7QQKFKAQ -e AWS_SECRET_ACCESS_KEY=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') {

      sh 'apk --update add terraform git'
      sh 'rm -rf aws'
      sh 'git clone https://github.com/cchen1103/aws.git'
      sh "terraform plan -var 'env=${params.env}' -input=false aws"

    }
  }

  stage('Build aws infrastructure') {
    /* Exec terraform build plan */

    def path
    path = pwd()
    tf {

      sh 'ls /tf'
      sh 'ls'
      sh 'pwd'

    }
  }
}
