node('master'){
  stage('Pull aws infra repo') {
    /* Pull aws infrastructure builder repo */

    def tf
    tf = docker.image('alpine').inside('--user=root') {

      sh 'apk --update add terraform git'
      sh 'rm -rf aws'
      sh 'git clone https://github.com/cchen1103/aws.git'
      sh "export AWS_ACCESS_KEY_ID=AKIAIV4TMSTZLVTMUMDA"
      sh "export AWS_SECRET_ACCESS_KEY=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"
      sh "terraform plan -var 'env=${params.env}' aws"

    }
  }

  stage('Show build plan') {
    /* Show terraform build plan */

    def path
    path = pwd()
    docker.image('alpine').inside("-v ${path}/tf:/tf --user=root") {

      sh 'apk --update add terraform'
      sh 'terraform init'
      sh 'ls /tf'
      sh 'ls'
      sh 'pwd'
      sh 'terraform plan /tf'

    }
  }
}
